name: Python Testing

on:
  push:
    branches:
      - tdd_04
  pull_request:
    branches:
      - tdd_04

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest 

      - name: Run tests
        run: |
          pytest tests/
